name: Continues Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,jsx,tsx,md}
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Jest
        run: |
          npm i
          npm test -- --passWithNoTests
      - name: Eslint
        run: npm run lint
